version: 3.9

services:
  mc:
    container_name: mc
    image: potion-mc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
